### PR TITLE
fix: Update to Unicode Standard Version 15.0

### PR DESCRIPTION
**Pull request by NicPWNs**
To update to the latest [Unicode Standard Version 15.0](https://unicode.org/Public/emoji/15.0/).

- [emoji-sequences.txt](https://unicode.org/Public/emoji/15.0/emoji-sequences.txt)
- [emoji-zwj-sequences.txt](https://unicode.org/Public/emoji/15.0/emoji-zwj-sequences.txt)

Used the code in [PR: Add all emojis #2](https://github.com/pketh/random-unicode-emoji/pull/2#issue-900327584) to generate.

@pketh, I also saw on [NPM](https://www.npmjs.com/package/random-unicode-emoji?activeTab=readme) that you are looking for someone to take over this project. I'd like to offer taking this project over to keep it up to date. It marries well with my [Python version of this](https://pypi.org/project/random-unicode-emoji/).

### CODE REVIEW

**Comment by pketh** [comment]
Hey nic, the changes look good and im def in favor of you taking this over

**Comment by pketh** [comment]
I tried to transfer this repo to you but I think it clashed with your fork bc I got the error 

> NicPWNs/random-unicode-emoji already exists

**Comment by NicPWNs** [comment]
Sounds great, thank you! Give it another try. Just deleted my fork.

**Comment by NicPWNs** [comment]
@pketh I got the transfer, thank you! ❤️ Are you able to transfer the [npm package](https://www.npmjs.com/package/random-unicode-emoji) to me too? I want to bump the latest version with the new Unicode 15.0 emojis. [Instructions for transfer are here](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account). My npm username is [nicpwns](https://www.npmjs.com/~nicpwns)

**Comment by pketh** [comment]
donezo

**Pull request merged**
