### PR TITLE
Add all emojis

### PR DESCRIPTION
**Pull request by angleKH**
Adds the rest of the emojis from https://unicode.org/Public/emoji/13.1/emoji-sequences.txt and https://unicode.org/Public/emoji/13.1/emoji-zwj-sequences.txt.

The hastily written JS snippet below was used to make the array in this PR for 13.1 of the standard and will be able to parse future revisions of the Unicode Emoji data files assuming the format remains the same, where `txt` is the content of the text file.
```javascript
JSON.stringify(txt.split("\n").map(s => s.trim()).filter(s => (s !== "") && !s.startsWith("#")).map(s => s.split(/\s*;\s*/g)[0].split("..")).map(a => {
	if (a.length > 1) {
		const start = a[0];
		const end = a[1];
		const new_a = [start];
		for (let i = parseInt(start,16)+1; i < parseInt(end,16); ++i) {
			new_a.push(i.toString(16));
		}
		return new_a;
	} else {
		return a;
	}
}).flat().map(s => {
	const codePoints = s.split(" ").map(s => parseInt(s,16));
	return String.fromCodePoint.apply(null, codePoints);
}));
```

### CODE REVIEW

**Comment by luc122c** [comment]
BUMP @pketh 
Please could you update this and the NPM listing. I'm happy to help!

**Comment by pketh** [comment]
Hey @angleKH , @luc122c 

sorry I totally missed this!

Comments below,

**Comment by pketh** [comment]
Oh I just read the pr, it looks good but 
Some Suggestions

- let’s remove all the modifier skin tone variations and just use yellow (the default) so that the randomness still feels randomly weighted? Alternatively, the user can specify a skin tone preference but that’s way more work. 
- should we bump this script again to run on a newer Unicode standard if avail?

if no one is interested in that I’m cool w merging this now. Lmk

**Comment by luc122c** [comment]
> let’s remove all the modifier skin tone variations and just use yellow (the default)

I think that's a good idea 👍

>  Alternatively, the user can specify a skin tone preference but that’s way more work.

Agreed, maybe a good idea for the future. If you make it an issue, perhaps I (or others) could have a crack at a PR

> should we bump this script again to run on a newer Unicode standard if avail?

Perhaps merge this one (sans skin tone modifiers) and then create another PR to bump it again?

BTW thanks for making this, it has been super useful for me 👍  I'm not familiar with publishing on NPM but please could you give me a ping when you update it so I can update it in my project 😀

**Comment by pketh** [comment]
hi I merged this and updated the version to `1.0.2` on npm https://www.npmjs.com/package/random-unicode-emoji (cc @luc122c )

**Pull request merged**
